[pytest]
markers =
    smoke: marker for running smoke tests.
    ui: marker for running ui tests.
    api: marker for running api tests.
    selenium: marker for running selenium tests.
    selene: marker for running selene tests.
addopts = -q